Table user {
  id bigserial [primary key]
  createdAt timestamp
  updatedAt timestamp
  name text
  surname text
  username text
  email text
  password text
}

Table questionnaire {
  id bigserial [pk]
  createdAt timestamp
  updatedAt timestamp
  topic text
  questions text
  userId bigserial
}

Ref: questionnaire.userId < user.id